void start();
void pressets();
void secretwordchoose();
void missdrawer();
void game();
void fguess();
int correcttry(char letter);
int lose();
int win();
int misscounter(char guess);
//int letteralreadyused(char guess);
int miss(); 